### ISSUE TITLE
no connection to xinetd agent

### ISSUE THREAD

**Issue by erikschwalbe** [debops-contrib/ansible-checkmk_agent#34]
Hi,

I run ansible-checkmk_agent role with option checkmk_agent__type: [ 'xinetd' ].
But connection from check_mk server did not work:
 `-> Failed: Empty output from agent at TCP port 6556`
on agent:
`libwrap refused connection to check_mk (libwrap=check_mk_agent)`
There are is one entry in /etc/hosts.allow and one in /etc/hosts.allow.d/50_inetd_allow:
inetd : <check_mk_server_ip>
After changing one of these entries to check_mk_agent : <check_mk_server_ip> the connection works like expected

Regards,
Erik

**Comment by ganto** [comment]
Did you run the role with the provided playbook? There we call out to the `debops.tcpwrappers` role which should handle that.

I'm not using `tcpwrappers` so it might be that there is an issue with the definition of `checkmk_agent__tcpwrappers__dependent_allow` or a bug in the tcpwrappers role itself.

**Comment by ganto** [comment]
I had a brief look at the code and there was nothing wrong that I could spot immediately. It seems that the `debops.tcpwrappers` role dependency is not executed (or with an empty allow list)

The intention from the following code is that:
```
checkmk_agent__tcpwrappers__dependent_allow:

  - daemon: 'inetd'
    comment: 'Ensure legacy tcpwrappers ACL is absent'
    by_role: 'debops-contrib.checkmk_agent'
    state: 'absent'

  - daemon:
      - 'check_mk_agent'
      - 'check_mk_caching_agent'
      ## Not required:
      # - 'inetd'
      # - 'xinetd'
    client: '{{ checkmk_agent__allow }}'
    accept_any: False
    weight: '50'
    comment: 'Allow remote connections to the Check_MK agent'
    by_role: 'debops-contrib.checkmk_agent'
    state: '{{ "present"
               if (("xinetd" in checkmk_agent__type) and
                   (checkmk_agent__deploy_state in ["present"]))
               else "absent" }}'
```
- Remove legacy ACL? This should remove the `/etc/hosts.allow.d/50_inetd_allow` that you mentioned. @ypid: As you authored a341925948549efad8cdced14c334dccd7c1f6b8, what's that for? Where does `/etc/hosts.allow.d/50_inetd_allow` come from respectively?
- Create a file `/etc/hosts.allow.d/50_checkmk_agent_allow` with the entry for the agent access.

@erikschwalbe Could you please check if `debops.tcpwrappers` is run in your case and what's the value of `checkmk_agent__tcpwrappers__dependent_allow` and `tcpwrappers__dependent_allow` in the context of that role?
