### ISSUE TITLE
not working on debian stretch

### ISSUE THREAD

**Issue by erikschwalbe** [debops-contrib/ansible-checkmk_agent#35]
We use only the ckeckmk_agent role, not the checkmk_server role!

I try to install on debian stretch but installation failed.
There is no check-mk-agent package in repository. 
The task: 
```
- name: Ensure specified packages are in there desired state
  package:
name: '{{ item }}'
```
tries to install the agent from the local repository.
So, for Ubuntu 16.04. there is only a very old package 1.2.6x
The task:
```
- include: setup_plugins.yml
tags: [ 'role::checkmk_agent:plugins' ]
```
clone the whole git repository to get the plugins...
On our standalone check-mk server there is a section agents and plugins. 
So I rewrite the the checkmk_agent and download the agent and the plugins from our check-mk server directly:
```
- name: Get latest agent version from check-mk-server
  shell: wget -q -O - https://<check-mk-server>/nagios/check_mk/agents/ | grep '\.deb' | cut -d'"' -f2
  register: checkmk_agent__register_latest_agent_version

- name: Install check-mk-agent
  apt:
    deb: https://<check-mk-server>/nagios/check_mk/agents/{{ checkmk_agent__register_latest_agent_version.stdout }}
```
and:
```
- name: Install Check_MK plugins
  get_url:
    url: 'https://nagios.canoo.com/nagios/check_mk/agents/plugins/{{ item }}'
    dest: '{{ checkmk_agent__plugin_path }}'
    mode: 0755
  with_items: '{{ checkmk_agent__combined_plugins }}'
```
Perhaps this is the better way? 
So server and agent uses the same version and you do not need to checkout the whole git repo.

Regards,
Erik
